pragma solidity ^0.4.22;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

contract Problem2 {
    uint256 maxValue = 4000000;
    

     function sumOfEvenFibonacci() public view returns(uint256) {
         uint256 sum;
         uint256 n = 100;
         
        uint256[] memory fibSequence = new uint256[](n+1);
        uint256 lastFib = 0;

        for (uint256 i=0; i <= n; i++) {
            if(i <= 1) {
                fibSequence[i] = i;
            } else {
                if(lastFib > maxValue) {
                    break;
                } else {
                    fibSequence[i] = fibSequence[i -1] + fibSequence[i -2];
                    lastFib = fibSequence[i];   
                    if(lastFib % 2 == 0) {
                        sum += lastFib;
                    }
                }
              
            }
        }

        return sum;
    }
}